version: '3'

services:

  mysql-dev:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: demodb
    ports:
      - 3308:3306

  admin:
      image: adminer
      ports:
        - 8080:8080
      links:
        - mysql-dev